class ParserError(Exception):
    """Исключение возникающее при полной невозможности дальнейшего парсинга."""

    pass
